[package]
name = "sway_cycler"
version = "0.1.0"
edition = "2024"
authors = ["santiago leal  ,<santiagojoseleal27@gmail.com>"]
description = "simple cycle sistem to sway"
license = "MIT" 
repository = "https://github.com/SJLS27/sway_cycler"
readme = "README.md"
categories = [
    "command-line-utilities",
    "gui"
]
keywords = ["sway", "wayland", "workspace", "wm", "i3"]


[dependencies]
clap = { version = "4.5", features = ["derive"] }
swayipc = "3.0"
